server:
  port: 8083
spring:
  application:
    name: fitness-demo
  datasource:
#      name: fit
      url: jdbc:mysql://localhost/fitness?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password: 1234

security:
  basic:
    enabled: false
  headers:
    frame: false

mybatis-plus:
  type-aliases-package: com.chengshi.fitness.dao
  mapper-locations: classpath*:mapper/**Mapper.xml
  global-config:
    id-type: 2
    field-strategy: 2
    refresh-mapper: true
    db-column-underline: false
  configuration:
    map-underscore-to-camel-case: false
    lazy-loading-enabled: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-column-label: false
    use-actual-param-name: false

