server:
  port: 1051
spring:
  application:
    name: qxs-monitor
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info


#eureka
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://user:password@eureka-dev:8761/eureka
management:
  security:
    enabled: false #关闭安全验证
logging:
  file: "logs/boot-admin-sample.log"
