server:
  port: 1021
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:./config
  profiles:
    active: native

#eureka
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://user:password@eureka-dev:8761/eureka
